//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkoMVCApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkoMVCApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj novi kontakt.
        /// </summary>
        public static string BTN_CreateNewContact {
            get {
                return ResourceManager.GetString("BTN_CreateNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši.
        /// </summary>
        public static string BTN_Delete {
            get {
                return ResourceManager.GetString("BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string BTN_Save {
            get {
                return ResourceManager.GetString("BTN_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        public static string BTN_Search {
            get {
                return ResourceManager.GetString("BTN_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjeni.
        /// </summary>
        public static string BTN_Update {
            get {
                return ResourceManager.GetString("BTN_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darko MVC App.
        /// </summary>
        public static string HDR_APP_NAME {
            get {
                return ResourceManager.GetString("HDR_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darko Subić.
        /// </summary>
        public static string HDR_AuthorName {
            get {
                return ResourceManager.GetString("HDR_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povratak na listu kontakata.
        /// </summary>
        public static string HDR_BackToList {
            get {
                return ResourceManager.GetString("HDR_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj novi kontakt.
        /// </summary>
        public static string HDR_CreateNewContact {
            get {
                return ResourceManager.GetString("HDR_CreateNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kreiranja.
        /// </summary>
        public static string HDR_DateCreated {
            get {
                return ResourceManager.GetString("HDR_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjeni postojeći kontakt.
        /// </summary>
        public static string HDR_EditExistingContact {
            get {
                return ResourceManager.GetString("HDR_EditExistingContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string HDR_FIrstName {
            get {
                return ResourceManager.GetString("HDR_FIrstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string HDR_Id {
            get {
                return ResourceManager.GetString("HDR_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string HDR_Insert {
            get {
                return ResourceManager.GetString("HDR_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string HDR_LastName {
            get {
                return ResourceManager.GetString("HDR_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string HDR_Mail {
            get {
                return ResourceManager.GetString("HDR_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string HDR_Telephone {
            get {
                return ResourceManager.GetString("HDR_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string HDR_Update {
            get {
                return ResourceManager.GetString("HDR_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kreiranja:.
        /// </summary>
        public static string LBL_DateCreated {
            get {
                return ResourceManager.GetString("LBL_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži po imenu ili prezimenu.
        /// </summary>
        public static string LBL_FindByFirstNameOrLastName {
            get {
                return ResourceManager.GetString("LBL_FindByFirstNameOrLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string LBL_FirstName {
            get {
                return ResourceManager.GetString("LBL_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        public static string LBL_LastName {
            get {
                return ResourceManager.GetString("LBL_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        public static string LBL_Mail {
            get {
                return ResourceManager.GetString("LBL_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon:.
        /// </summary>
        public static string LBL_Telephone {
            get {
                return ResourceManager.GetString("LBL_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kontakata.
        /// </summary>
        public static string PG_ContactList {
            get {
                return ResourceManager.GetString("PG_ContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upis kontakta.
        /// </summary>
        public static string PG_InsertPage {
            get {
                return ResourceManager.GetString("PG_InsertPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena kontakta.
        /// </summary>
        public static string PG_UpdatePage {
            get {
                return ResourceManager.GetString("PG_UpdatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obvezan podatak!.
        /// </summary>
        public static string VLD_FirstNameRequired {
            get {
                return ResourceManager.GetString("VLD_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obvezan podatak!.
        /// </summary>
        public static string VLD_LastNameRequired {
            get {
                return ResourceManager.GetString("VLD_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail nije unesen u ispravnom obliku.
        /// </summary>
        public static string VLD_MailValid {
            get {
                return ResourceManager.GetString("VLD_MailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon je obvezan podatak!.
        /// </summary>
        public static string VLD_TelephoneRequired {
            get {
                return ResourceManager.GetString("VLD_TelephoneRequired", resourceCulture);
            }
        }
    }
}
